Linkofy/Models/Link.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Linkofy.Models
{
    public class Link
    {
        public enum Live
        {
            Yes, No
        }

        public int LinkID { get; set; }
       

        [Required]
        [Display(Name = "Linking Page")]
        public string Obdomain { get; set; }

        
        public int? ClientID { get; set; }
        public virtual Client Client { get; set; }

        [Required]
        [Display(Name = "Outbound Link")]
        public string Obpage { get; set; }

        [Required]
        [Display(Name = "Anchor Text")]
        public string Anchor { get; set; }

        [Required]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Date Built")]
        [DataType(DataType.Date)]
        public DateTime BuildDate { get; set; }

        public Live? live { get; set; }

        public int IdentifierID { get; set; }
        public virtual Identifier Identifier { get; set; }

        public int? UserTableID { get; set; }
        public virtual UserTable UserTable { get; set; }

    }
}

Linkofy/Controllers/LinksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Linkofy.Models;
using Microsoft.AspNet.Identity;
using Linkofy.Functions;
using CsvHelper;
using System.IO;
using PagedList;
using Newtonsoft.Json;

namespace Linkofy.Controllers
{
    [Authorize]
    public class LinksController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Links
        [Authorize]
        public ActionResult Index(string sortOrder, int? page, string searchString, string currentFilter)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.DomainSortParm = String.IsNullOrEmpty(sortOrder) ? "Dom_desc" : "";
            ViewBag.LinkSortParm = sortOrder == "Link" ? "Link_desc" : "Link";
            ViewBag.ClientSortParm = sortOrder == "Clie" ? "Clie_desc" : "Clie";
            ViewBag.OBSortParm = sortOrder == "OB" ? "OB_desc" : "OB";
            ViewBag.AnchorSortParm = sortOrder == "Anc" ? "Anc_desc" : "Anc";
            ViewBag.TypeSortParm = sortOrder == "Type" ? "Type_desc" : "Type";
            ViewBag.BuildSortParm = sortOrder == "Buil" ? "Buil_desc" : "Buil";
            var links = db.Links.Include(l => l.Client).Include(l => l.Identifier).Include(l => l.UserTable);

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            switch (sortOrder)
            {
                case "Dom_desc":
                    links = links.OrderByDescending(s => s.Identifier.domain);
                    break;
                case "Link":
                    links = links.OrderBy(s => s.Obdomain);
                    break;
                case "Link_desc":
                    links = links.OrderByDescending(s => s.Obdomain);
                    break;
                case "Clie":
                    links = links.OrderBy(s => s.Client.clientN);
                    break;
                case "Clie_desc":
                    links = links.OrderByDescending(s => s.Client.clientN);
                    break;
                case "OB":
                    links = links.OrderBy(s => s.Obpage);
                    break;
                case "OB_desc":
                    links = links.OrderByDescending(s => s.Obpage);
                    break;
                case "Anc":
                    links = links.OrderBy(s => s.Anchor);
                    break;
                case "Anc_desc":
                    links = links.OrderByDescending(s => s.Anchor);
                    break;
                case "Type":
                    links = links.OrderBy(s => s.Identifier.type);
                    break;
                case "Type_desc":
                    links = links.OrderByDescending(s => s.Identifier.type);
                    break;
                case "Buil":
                    links = links.OrderBy(s => s.BuildDate);
                    break;
                case "Buil_desc":
                    links = links.OrderByDescending(s => s.BuildDate);
                    break;
                default:
                    links = links.OrderBy(s => s.Identifier.domain);
                    break;
            }
            int pageSize = 30;
            int pageNumber = (page ?? 1);
            var userId = User.Identity.GetUserId();
            var UserTableID = db.UserTables.Where(c => c.ApplicationUserId == userId).First().ID;
            ViewBag.UserTableID = UserTableID;
            ViewBag.Userid = userId;
            return View(links.ToPagedList(pageNumber, pageSize));
        }

        // GET: Links/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Link link = db.Links.Find(id);
            if (link == null)
            {
                return HttpNotFound();
            }
            return View(link);
        }

        // GET: Links/Create
        [Authorize]
        public ActionResult Create()
        {
            var userId = User.Identity.GetUserId();
            var UserTableID = db.UserTables.Where(c => c.ApplicationUserId == userId).First().ID;
            ViewBag.ClientID = new SelectList(db.Clients.Where(c => c.UserTableID == UserTableID), "ID", "clientN");
            ViewBag.IdentifierID = new SelectList(db.Identifiers.Where(c => c.UserTableID == UserTableID), "ID", "domain");
            return View();
        }

        // POST: Links/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Link model)
        {
            if (ModelState.IsValid)
            {
                var userId = User.Identity.GetUserId();
                var UserTableID = db.UserTables.Where(c => c.ApplicationUserId == userId).First().ID;

                Uri Obdomain = new Uri(model.Obdomain);
                string baseUri = Obdomain.GetLeftPart(System.UriPartial.Authority);
                Uri Obpage = new Uri(model.Obpage);
                string basiUri = Obpage.GetLeftPart(System.UriPartial.Authority);

                string pageContent = null;
                HttpWebRequest myReq = (HttpWebRequest)WebRequest.Create(baseUri + model.Obdomain.Replace(baseUri, ""));
                HttpWebResponse myres = (HttpWebResponse)myReq.GetResponse();

                using (StreamReader sr = new StreamReader(myres.GetResponseStream()))
                {
                    pageContent = sr.ReadToEnd();
                }

                string live = "";
                if (pageContent.Contains(model.Obpage))
                {
                    live = "Yes";
                }
                else { live = "No"; }

                var link = new Link { Obdomain = model.Obdomain.Replace(baseUri,""), ClientID = model.ClientID, Obpage = model.Obpage.Replace(basiUri, ""), BuildDate = model.BuildDate, Anchor = model.Anchor, IdentifierID = model.IdentifierID, live = (Link.Live)Enum.Parse(typeof(Link.Live), live), UserTableID = UserTableID };
                ViewBag.link = link;
                db.Links.Add(link);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ClientID = new SelectList(db.Clients, "ID", "clientN", model.ClientID);
            ViewBag.IdentifierID = new SelectList(db.Identifiers, "ID", "domain", model.IdentifierID);
            return View(ViewBag.link);
        }
        public ActionResult CreateBulk()
        {
            return View();
        }
        [HttpPost]
        [ActionName("CreateBulk")]
        public ActionResult CreateBulkUpload(Link model)
        {
            var file = Request.Files["attachmentcsv"];
            using (var csv = new CsvReader(new StreamReader(file.InputStream), true))
            {
                csv.Configuration.HeaderValidated = null;
                csv.Configuration.MissingFieldFound = null;
                var records = csv.GetRecords<Link>().ToList();
                foreach (var item in records)
                {
                    if (!(from c in db.Links
                          select c.Obdomain).Contains(item.Obdomain) && !(from c in db.Links select c.Obpage).Contains(item.Obpage))
                    {
                        var userId = User.Identity.GetUserId();
                        var UserTableID = db.UserTables.Where(c => c.ApplicationUserId == userId).First().ID;
                        Uri Obdomain = new Uri(item.Obdomain);
                        string baseUri = Obdomain.GetLeftPart(System.UriPartial.Authority);
                        Uri Obpage = new Uri(item.Obpage);
                        string basiUri = Obpage.GetLeftPart(System.UriPartial.Authority);
                        int domainID = db.Identifiers.Where(c => c.domain.Contains(baseUri.Substring(8, 14))).First().ID;
                        int clientID = db.Clients.Where(c => c.homePage.Contains(basiUri.Substring(8, 14))).First().ID;

                        var link = new Link
                        {
                            Obdomain = item.Obdomain.Replace(baseUri,""),
                            Obpage = item.Obpage.Replace(baseUri, ""),
                            BuildDate = item.BuildDate,
                            Anchor = item.Anchor,
                            IdentifierID = domainID,
                            ClientID = clientID,
                            UserTableID = UserTableID
                        };
                    ViewBag.link = link;
                        db.Links.Add(link);
                        db.SaveChanges();
                    }
                    else { continue; }
                }
                return RedirectToAction("Index");
            }
        }
        // GET: Links/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Link link = db.Links.Find(id);
            if (link == null)
            {
                return HttpNotFound();
            }
            var userId = User.Identity.GetUserId();
            var UserTableID = db.UserTables.Where(c => c.ApplicationUserId == userId).First().ID;
            ViewBag.ClientID = new SelectList(db.Clients.Where(c => c.UserTableID == UserTableID), "ID", "clientN", link.ClientID);

Linkofy/Views/Links/Create.cshtml
@model Linkofy.Models.Link

@{
    ViewBag.Title = "Create";
}
@section Styles {
    <link href="@Url.Content("~/Styles/Edit.css")" rel="stylesheet" type="text/css" />
}

<h1>Add Link</h1>

<p class="options">@Html.ActionLink("Back to List", "Index")</p>

    
   <div class="row">
            <div class="col-md-offset-3 col-md-6">

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
<br />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Obdomain, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.Obdomain, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Obdomain, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClientID, "ClientID", htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.DropDownList("ClientID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ClientID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Obpage, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.Obpage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Obpage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Anchor, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.Anchor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Anchor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BuildDate, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.BuildDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BuildDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdentifierID, "IdentifierID", htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.DropDownList("IdentifierID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdentifierID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserTableID, "UserTableID", htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.DropDownList("UserTableID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserTableID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-10 col-md-4">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
</div>
       </div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Linkofy/Views/Links/CreateBulk.cshtml
@model Linkofy.Models.Identifier

@{
    ViewBag.Title = "CreateBulk";
}
    @section Styles {
    <link href="@Url.Content("~/Styles/Bulk.css")" rel="stylesheet" type="text/css" />
}

<h1>Add Bulk Links</h1>
<p class="options">@Html.ActionLink("Back to List", "Index")</p>

<div class="col-md-12">
    <br />
<p class="options">Write your CSV using the column headers below each definition and upload it.</p>
<table class="table">
    <tr>
        <th>
            Linking Page (not domain)
        </th>
        <th>
            Outbound Link
        </th>
        <th>
            Anchor Text
        </th>
        <th>
            Date Built
        </th>
    </tr>
    <tr>
        <td>
            Obdomain
        </td>
        <td>
            Obpage
        </td>
                <td>
            Anchor
        </td>
        <td>
            BuildDate
        </td>
    </table>

    <br />
    @using (Html.BeginForm("CreateBulk", "Links", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="form-group">
            <label for="attachment">Select a Csv File</label>
            <label class="btn btn-default btn-file">
                <input type="file" name="attachmentcsv" id="attachmentcsv" hidden>
            </label>
        </div>
        <button type="submit" class="btn btn-primary">Upload</button>
    }
</div>

Linkofy/Views/Links/Delete.cshtml
@model Linkofy.Models.Link

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Link</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Client.clientN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Client.clientN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Identifier.domain)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Identifier.domain)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserTable.userIdentity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserTable.userIdentity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Obdomain)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Obdomain)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Obpage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Obpage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Anchor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Anchor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BuildDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BuildDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Linkofy/Views/Links/Details.cshtml
@model Linkofy.Models.Link

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Link</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Client.clientN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Client.clientN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Identifier.domain)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Identifier.domain)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserTable.userIdentity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserTable.userIdentity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Obdomain)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Obdomain)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Obpage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Obpage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Anchor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Anchor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BuildDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BuildDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.LinkID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Linkofy/Views/Links/Edit.cshtml
@model Linkofy.Models.Link

@{
    ViewBag.Title = "Edit";
}

@section Styles {
    <link href="@Url.Content("~/Styles/Edit.css")" rel="stylesheet" type="text/css" />
}

<h1>Edit Link</h1>

<p class="options">@Html.ActionLink("Back to List", "Index")</p>

    
   <div class="row">
            <div class="col-md-offset-3 col-md-6">

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
<br />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.LinkID)

        <div class="form-group">
            @Html.LabelFor(model => model.Obdomain, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.Obdomain, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Obdomain, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClientID, "ClientID", htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.DropDownList("ClientID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ClientID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Obpage, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.Obpage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Obpage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Anchor, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.Anchor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Anchor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BuildDate, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.BuildDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BuildDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdentifierID, "IdentifierID", htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.DropDownList("IdentifierID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdentifierID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserTableID, "UserTableID", htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.DropDownList("UserTableID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserTableID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-10 col-md-4">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
                </div>
       </div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Linkofy/Views/Links/Index.cshtml
@model IEnumerable<Linkofy.Models.Link>

@{
    ViewBag.Title = "Index";
}
        @section Styles {
    <link href="@Url.Content("~/Styles/Index.css")" rel="stylesheet" type="text/css" />
}
<h1>Links Built</h1>

<p class="options"> @Html.ActionLink("Add New", "Create")  |   @Html.ActionLink("Add Bulk", "Create") </p>

       <div class="row">
            <div class="col-lg-12">
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Identifier.domain)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Obdomain)
        </th>
                <th>
            @Html.DisplayNameFor(model => model.Client.clientN)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Obpage)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Anchor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BuildDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model.Where(p=>p.UserTable.ID == ViewBag.UserTableID)) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Identifier.domain)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Obdomain)
        </td>
                <td>
            @Html.DisplayFor(modelItem => item.Client.clientN)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Obpage)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Anchor)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BuildDate.Date)
        </td>
        <td>
            @Html.ActionLink(" ", "Details", new { id=item.LinkID }, new {@class= "glyphicon glyphicon-home" })
            @Html.ActionLink(" ", "Edit", new { id=item.LinkID }, new {@class= "glyphicon glyphicon-edit" }) 
            @Html.ActionLink(" ", "Delete", new { id=item.LinkID }, new {@class= "glyphicon glyphicon-trash" })
        </td>
    </tr>
}

</table>
                </div>
           </div>