Linkofy/Models/Identifier.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Linkofy.Models
{
    public class Identifier
    {
    public enum Ltype
        {
            GuestPost, ExistingLink
        }

        public int ID { get; set; }

        [Required]
        [Display(Name = "Domain")]
        public string domain { get; set; }

        [Required]
        [Display(Name = "Contact Email")]
        [EmailAddress]
        public string contact { get; set; }

        [Display(Name = "Contact Name")]
        public string contactname { get; set; }

        [Required]
        [Display(Name = "Price")]
        public int price { get; set; }

        [Display(Name = "Type of Link")]
        public Ltype? type { get; set; }

        [Display(Name = "TF")]
        public int TrustFlow { get; set; }

        [Display(Name = "CF")]
        public int CitationFlow { get; set; }

        [Display(Name = "RIPs")]
        public int RI { get; set; }

        public int? MJTopicsID { get; set; }
        public virtual MJTopics MJTopics { get; set; }

        public virtual UserTable UserTable { get; set; }
        public int UserTableID { get; set; }

        public virtual ICollection<Link> Links { get; set; }
    }
}

Linkofy/Controllers/IdentifiersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Linkofy.Models;
using System.IO;
using Newtonsoft.Json.Linq;
using System.Text;
using Microsoft.AspNet.Identity;
using Linkofy.Functions;
using CsvHelper;
using System.Net.Mail;
using Newtonsoft.Json;
using PagedList;

namespace Linkofy.Controllers
{
    [Authorize]
    public class IdentifiersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Identifiers
        [Authorize]
        public ActionResult Index(string sortOrder, int? page, string currentFilter, string searchString)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.DomainSortParm = String.IsNullOrEmpty(sortOrder) ? "Dom_desc" : "";
            ViewBag.ContactESortParm = sortOrder == "ContE" ? "ContE_desc" : "ContE";
            ViewBag.ContNSortParm = sortOrder == "ContN" ? "ContN_desc" : "ContN";
            ViewBag.PriceSortParm = sortOrder == "Price" ? "Price_desc" : "Price";
            ViewBag.TypeSortParm = sortOrder == "Type" ? "Type_desc" : "Type";
            ViewBag.TFSortParm = sortOrder == "TF" ? "TF_desc" : "TF";
            ViewBag.CFSortParm = sortOrder == "CF" ? "CF_desc" : "CF";
            ViewBag.RISortParm = sortOrder == "RI" ? "RI_desc" : "RI";
            ViewBag.MJSortParm = sortOrder == "MJ" ? "MJ_desc" : "MJ";
            var identifiers = db.Identifiers.Include(i => i.MJTopics).Include(i => i.UserTable);

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            switch (sortOrder)
            {
                case "Dom_desc":
                    identifiers = identifiers.OrderByDescending(s => s.domain);
                    break;
                case "ContE":
                    identifiers = identifiers.OrderBy(s => s.contact);
                    break;
                case "ContE_desc":
                    identifiers = identifiers.OrderByDescending(s => s.contact);
                    break;
                case "ContN":
                    identifiers = identifiers.OrderBy(s => s.contactname);
                    break;
                case "ContN_desc":
                    identifiers = identifiers.OrderByDescending(s => s.contactname);
                    break;
                case "Price":
                    identifiers = identifiers.OrderBy(s => s.price);
                    break;
                case "Price_desc":
                    identifiers = identifiers.OrderByDescending(s => s.price);
                    break;
                case "Type":
                    identifiers = identifiers.OrderBy(s => s.type);
                    break;
                case "Type_desc":
                    identifiers = identifiers.OrderByDescending(s => s.type);
                    break;
                case "TF":
                    identifiers = identifiers.OrderBy(s => s.TrustFlow);
                    break;
                case "TF_desc":
                    identifiers = identifiers.OrderByDescending(s => s.TrustFlow);
                    break;
                case "CF":
                    identifiers = identifiers.OrderBy(s => s.CitationFlow);
                    break;
                case "CF_desc":
                    identifiers = identifiers.OrderByDescending(s => s.CitationFlow);
                    break;
                case "RI":
                    identifiers = identifiers.OrderBy(s => s.RI);
                    break;
                case "RI_desc":
                    identifiers = identifiers.OrderByDescending(s => s.RI);
                    break;
                case "MJ":
                    identifiers = identifiers.OrderBy(s => s.MJTopics.topicalTF);
                    break;
                case "MJ_desc":
                    identifiers = identifiers.OrderByDescending(s => s.MJTopics.topicalTF);
                    break;
                default:
                    identifiers = identifiers.OrderBy(s => s.domain);
                    break;
            }
            int pageSize = 30;
            int pageNumber = (page ?? 1);
            var userId = User.Identity.GetUserId();
            var UserTableID = db.UserTables.Where(c => c.ApplicationUserId == userId).First().ID;
            ViewBag.UserTableID = UserTableID;
            ViewBag.Userid = userId;
            return View(identifiers.ToPagedList(pageNumber, pageSize));
        }

        // GET: Identifiers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Identifier identifier = db.Identifiers.Find(id);
            if (identifier == null)
            {
                return HttpNotFound();
            }
            return View(identifier);
        }
        public ActionResult Available(int? id)
        {
            var userId = User.Identity.GetUserId();
            var UserTableID = db.UserTables.Where(c => c.ApplicationUserId == userId).First().ID;
            ViewBag.UserTableID = UserTableID;
            ViewBag.Userid = userId;
            ViewBag.DomainN = db.Identifiers.Where(c => c.ID == id).FirstOrDefault().domain;
            ViewBag.DomainD = id;

            var clients = (from i in db.Clients.Include(i => i.MJTopics).Include(i => i.UserTable).AsQueryable()
                           join l in db.Links.AsQueryable() on new { ID = i.ID, ClientID = id } equals new { ID = l.IdentifierID, ClientID = l.ClientID } into jL
                           where jL.Count() == 0
                           select i);
            return View(clients.ToList());
        }
        // GET: Identifiers/Create
        public ActionResult Create()
        {
            ViewBag.MJTopicsID = new SelectList(db.MJTopicss, "ID", "topicalTF");
            ViewBag.UserTableID = new SelectList(db.UserTables, "ID", "userIdentity");
            return View();
        }

        // POST: Identifiers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Identifier model)
        {
            if (ModelState.IsValid)
            {
                String Strip = model.domain.Replace("https://www.", "").Replace("http://www.", "").Replace("https://", "").Replace("http://", "").Replace("www.", "");
                string[] URLtests = { "https://www." + Strip, "http://www." + Strip, "https://" + Strip, "http://" + Strip };
                string[] Metric = MajesticFunctions.MajesticChecker(URLtests);
                var userId = User.Identity.GetUserId();
                var UserTableID = db.UserTables.Where(c => c.ApplicationUserId == userId).First().ID;
                var identifier = new Identifier { domain = Metric[0], contact = model.contact, contactname = model.contactname.First().ToString().ToUpper() + model.contactname.Substring(1), price = model.price, type = model.type, TrustFlow = Int32.Parse(Metric[1]), CitationFlow = Int32.Parse(Metric[2]), RI = Int32.Parse(Metric[3]), MJTopicsID = model.MJTopicsID, UserTableID = UserTableID };
                ViewBag.identifier = identifier;
                db.Identifiers.Add(identifier);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MJTopicsID = new SelectList(db.MJTopicss, "ID", "ID", model.MJTopicsID);
            ViewBag.UserTableID = new SelectList(db.UserTables, "ID", "userIdentity", model.UserTableID);
            return View(ViewBag.identifier);
        }
        public ActionResult CreateBulk()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("CreateBulk")]
        public ActionResult CreateBulkUpload(Identifier model)
        {
            var file = Request.Files["attachmentcsv"];
            using (var csv = new CsvReader(new StreamReader(file.InputStream), true))
            {
                csv.Configuration.HeaderValidated = null;
                csv.Configuration.MissingFieldFound = null;
                var records = csv.GetRecords<Identifier>().ToList();
                foreach (var item in records)
                {
                    var strip = item.domain.Replace("https://www.", "").Replace("http://www.", "")
                       .Replace("https://", "").Replace("http://", "").Replace("www.", "");

                    string[] URLtests =
                       {"https://www." + strip, "http://www." + strip, "https://" + strip, "http://" + strip};

                    string[] Metric = MajesticFunctions.MajesticChecker(URLtests);

                    if (!(from c in db.Identifiers
                          select c.domain).Contains(Metric[0]))
                    {
                        var userId = User.Identity.GetUserId();
                        var UserTableID = db.UserTables.Where(c => c.ApplicationUserId == userId).First().ID;

                        var identifier = new Identifier
                        {
                            domain = Metric[0],
                            contact = item.contact,
                            contactname = item.contactname.First().ToString().ToUpper() + item.contactname.Substring(1),
                            price = item.price,
                            type = item.type,
                            TrustFlow = Int32.Parse(Metric[1]),
                            CitationFlow = Int32.Parse(Metric[2]),
                            RI = Int32.Parse(Metric[3]),

Linkofy/Views/Identifiers/Available.cshtml
@model IEnumerable<Linkofy.Models.Identifier>

@{
    ViewBag.Title = "Available";
}
        @section Styles {
    <link href="@Url.Content("~/Styles/Index.css")" rel="stylesheet" type="text/css" />
}

<h1>Available</h1>

<p class="options">
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MJTopics.topicalTF)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserTable.userIdentity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.domain)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.contact)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.contactname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TrustFlow)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CitationFlow)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RI)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model.Where(Model.Links.Item => item.ClientID != 1)) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.MJTopics.topicalTF)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserTable.userIdentity)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.domain)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.contact)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.contactname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.type)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TrustFlow)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CitationFlow)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RI)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

Linkofy/Views/Identifiers/Create.cshtml
@model Linkofy.Models.Identifier

@{
    ViewBag.Title = "Create";
}
@section Styles {
    <link href="@Url.Content("~/Styles/Edit.css")" rel="stylesheet" type="text/css" />
}

<h1>Create Domain</h1>

<p class="options">@Html.ActionLink("Back to List", "Index")</p>

    
   <div class="row">
            <div class="col-md-offset-3 col-md-6">

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
 <br>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.domain, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.domain, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.domain, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.contact, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.contact, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.contact, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.contactname, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.contactname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.contactname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.price, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.type, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EnumDropDownListFor(model => model.type, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.type, "", new { @class = "text-danger" })
            </div>
        </div>

                <div class="form-group">
            @Html.LabelFor(model => model.MJTopicsID, "Topic", htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.DropDownList("MJTopicsID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MJTopicsID, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-10 col-md-4">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
</div>
       </div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Linkofy/Views/Identifiers/CreateBulk.cshtml
@model Linkofy.Models.Identifier

@{
    ViewBag.Title = "CreateBulk";
}
    @section Styles {
    <link href="@Url.Content("~/Styles/Bulk.css")" rel="stylesheet" type="text/css" />
}

<h1>Add Bulk Domains</h1>
<p class="options">@Html.ActionLink("Back to List", "Index")</p>

<div class="col-md-12">
    <br />
<p class="options">Write your CSV using the column headers below each definition and upload it.</p>
<table class="table">
    <tr>
        <th>
            Domain
        </th>
        <th>
            Contact Email
        </th>
        <th>
            Contact Name
        </th>
        <th>
            Price
        </th>
        <th>
            Type
        </th>
                <th>
            Topic ID
        </th>
    </tr>
    <tr>
        <td>
            domain
        </td>
        <td>
            contact
        </td>
        <td>
            contactname
        </td>
                <td>
            price
        </td>
        <td>
            type
        </td>
                <td>
            MJTopicsID
        </td>
    </tr>
        <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>
            <p>0 = GuestPost</p>
            <p>1 = ExistingLink</p>
        </td>
        <td></td>
                <td></td>
        <td></td>
                <td></td>
    </tr>
    </table>
    <br>
<table class="table">
<tbody>
    <tr>
<th>MJTopicsID</th>
<th>Topic</th>
</tr>
<tr>
<td>1</td>
<td>Adult</td>
</tr>
<tr>
<td>2</td>
<td>Arts</td>
</tr>
<tr>
<td>3</td>
<td>Business</td>
</tr>
<tr>
<td>4</td>
<td>Computers</td>
</tr>
<tr>
<td>5</td>
<td>General</td>
</tr>
<tr>
<td>6</td>
<td>Games</td>
</tr>
<tr>
<td>7</td>
<td>Green</td>
</tr>
<tr>
<td>8</td>
<td>Life</td>
</tr>
<tr>
<td>9</td>
<td>Fashion</td>
</tr>
<tr>
<td>10</td>
<td>Fitness</td>
</tr>
<tr>
<td>11</td>
<td>Health</td>
</tr>
<tr>
<td>12</td>
<td>Home</td>
</tr>
<tr>
<td>13</td>
<td>Jewellery</td>
</tr>
<tr>
<td>14</td>
<td>Marketing</td>
</tr>
<tr>
<td>15</td>
<td>News</td>
</tr>
<tr>
<td>16</td>
<td>Recreation</td>
</tr>
<tr>
<td>17</td>
<td>Reference</td>
</tr>
<tr>
<td>18</td>
<td>Regional</td>
</tr>
<tr>
<td>19</td>
<td>Science</td>
</tr>
<tr>
<td>20</td>
<td>Shopping</td>
</tr>
<tr>
<td>21</td>
<td>Society</td>
</tr>
<tr>
<td>22</td>
<td>Sports</td>
</tr>
<tr>
<td>23</td>
<td>Technology</td>
</tr>
<tr>
<td>24</td>
<td>Vehicles</td>
</tr>
<tr>
<td>25</td>
<td>Wedding</td>
</tr>
<tr>
<td>26</td>
<td>World</td>
</tr>
</tbody>
</table>
    <br />
    @using (Html.BeginForm("CreateBulk", "Identifiers", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="form-group">
            <label for="attachment">Select a Csv File</label>
            <label class="btn btn-default btn-file">
                <input type="file" name="attachmentcsv" id="attachmentcsv" hidden>
            </label>
        </div>
        <button type="submit" class="btn btn-primary">Upload</button>
    }
</div>

Linkofy/Views/Identifiers/Delete.cshtml
@model Linkofy.Models.Identifier

@{
    ViewBag.Title = "Delete";
}
@section Styles {
    <link href="@Url.Content("~/Styles/Details.css")" rel="stylesheet" type="text/css" />
}

<h1>Delete @Html.DisplayFor(model => model.domain)</h1>

<div class="row">
    <div class="col-md-12">
        <table class="displayrow">
            <tr><th><h3>@Html.DisplayNameFor(model => model.contactname)</h3></th>
                <th><h3>@Html.DisplayNameFor(model => model.contact)</h3></th>
                <th><h3>@Html.DisplayNameFor(model => model.price)</h3></th>
                <th><h3>@Html.DisplayNameFor(model => model.type)</h3></th>
                <th><h3>@Html.DisplayNameFor(model => model.TrustFlow)</h3></th>
                <th><h3>@Html.DisplayNameFor(model => model.CitationFlow)</h3></th>
                <th><h3>@Html.DisplayNameFor(model => model.RI)</h3></th>
                <th><h3>@Html.DisplayNameFor(model => model.MJTopics.topicalTF)</h3></th>
            </tr>
            <tr><td><h4>@Html.DisplayFor(model => model.contactname)</h4></td>
                <td><h4>@Html.DisplayFor(model => model.contact)</h4></td>
                <td><h4>@Html.DisplayFor(model => model.price)</h4></td>
                <td><h4>@Html.DisplayFor(model => model.type)</h4></td>
                <td><h4>@Html.DisplayFor(model => model.TrustFlow)</h4></td>
                <td><h4>@Html.DisplayFor(model => model.CitationFlow)</h4></td>
                <th><h4>@Html.DisplayFor(model => model.RI)</h4></th>
                <td><h4>@Html.DisplayFor(model => model.MJTopics.topicalTF)</h4></td>
            </tr>
        </table>
    </div>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

    <p class="options">Are you sure you want to delete this domain?</p>

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default btn-lg" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Linkofy/Views/Identifiers/Details.cshtml
@model Linkofy.Models.Identifier

@{
    ViewBag.Title = "Details";
}
@section Styles {
    <link href="@Url.Content("~/Styles/Details.css")" rel="stylesheet" type="text/css" />
}

<h1>@Html.DisplayFor(model => model.domain)</h1>
<p class="options">@Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |  @Html.ActionLink("Back to List", "Index")</p>

<div class="row">
    <div class="col-md-12">
        <table class="displayrow">
            <tr><th><h3>@Html.DisplayNameFor(model => model.contactname)</h3></th>
                <th><h3>@Html.DisplayNameFor(model => model.contact)</h3></th>
                <th><h3>@Html.DisplayNameFor(model => model.price)</h3></th>
                <th><h3>@Html.DisplayNameFor(model => model.type)</h3></th>
                <th><h3>@Html.DisplayNameFor(model => model.TrustFlow)</h3></th>
                <th><h3>@Html.DisplayNameFor(model => model.CitationFlow)</h3></th>
                <th><h3>@Html.DisplayNameFor(model => model.RI)</h3></th>
                <th><h3>@Html.DisplayNameFor(model => model.MJTopics.topicalTF)</h3></th>
            </tr>
            <tr><td><h4>@Html.DisplayFor(model => model.contactname)</h4></td>
                <td><h4>@Html.DisplayFor(model => model.contact)</h4></td>
                <td><h4>@Html.DisplayFor(model => model.price)</h4></td>
                <td><h4>@Html.DisplayFor(model => model.type)</h4></td>
                <td><h4>@Html.DisplayFor(model => model.TrustFlow)</h4></td>
                <td><h4>@Html.DisplayFor(model => model.CitationFlow)</h4></td>
                <th><h4>@Html.DisplayFor(model => model.RI)</h4></th>
                <td><h4>@Html.DisplayFor(model => model.MJTopics.topicalTF)</h4></td>
            </tr>
        </table>
    </div>
        </div>

    <div class="col-md-12">
<h3>Links Built</h3>
        <table class="table">
            <tr>
                <th>Page Containing Link</th>
                <th>Client</th>
                <th>Outbound URL</th>
                <th>Anchor Text</th>
                <th>Date</th>
                <th>Action</th>
                    </tr>

            @foreach (var item in Model.Links) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Obdomain)
                </td>
                                          <td>
                    @Html.DisplayFor(modelItem => item.Client.clientN)
                </td>
                                                          <td>
                    @Html.DisplayFor(modelItem => item.Obpage)
                </td>
                                <td>
                    @Html.DisplayFor(modelItem => item.Anchor)
                </td>
                          <td>
                    @Html.DisplayFor(modelItem => item.BuildDate.Date)
                </td>
                                                        <td>
            @Html.ActionLink("Edit", "Edit", "Status", new { id=item.LinkID }) |
            @Html.ActionLink("Domain", "Details", "Status", new { id=item.LinkID }) |
            @Html.ActionLink("Delete", "Delete", "Status", new { id=item.LinkID })
        </td>
            </tr>
            }
        </table>
</div>

Linkofy/Views/Identifiers/SendMail.cshtml
@model Linkofy.Models.EmailAccount

@{
    ViewBag.Title = "SendMail";
}
@section Styles {
    <link href="@Url.Content("~/Styles/Edit.css")" rel="stylesheet" type="text/css" />
}
@section Scripts {
  <script src="@Url.Content("~/Javascript/SendEmail.js")"></script>
}

<h1>Send Outreach Email</h1>

    <div class="row">
            <div class="col-md-offset-3 col-md-6">
    @using (Html.BeginForm("SendMail", "Identifiers", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
    @Html.AntiForgeryToken()

            <div class="form-horizontal">
                        <div class="form-group">
             Email Address: <br />
                @Html.DropDownList("emailAddress", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.emailAddress, "", new { @class = "text-danger" })
        </div>
          <div class="form-group">
               To:<br />
               @Html.TextBox("toemail", ViewData["contactemail"], new { @class = "form-control" })
              </div>
                          <div class="form-group">
               To Name:<br />
               @Html.TextBox("toname", ViewData["contactname"], new { @class = "form-control" })
              </div>
                                        <div class="form-group">
             Template: <br />
                @Html.DropDownList("templateName", null, htmlAttributes: new { @class = "form-control" })
        </div>

          
          <div class="form-group">
              Subject:<br />
                @Html.TextBox("subject", ViewData["subject"], new { @class = "form-control" })
              </div>
                          <div class="form-group">
                              Body:<br />
 
                @Html.TextArea("body", ViewData["body"].ToString(), new { @class = "form-control" })
              </div>
        <button type="submit" class="btn btn-primary">Submit</button>
        </div>
            }
        </div>
        </div>